server:
  port: 8080
mysql:
  host: localhost
  port: 3306
  user: root
  password: 1234
  database: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  level: debug
  file_path: ./logs/dev.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true