server:
  port: 8082

databases:
  - user: admin
    password: 1234
    host: localhost
    dbName: shopDEV
  - user: toan
    password: 1234
    host: localhost
    dbName: shopDEV
security:
  jwt:
    key: abc1234