// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-simple-api/internal/controller"
	"go-simple-api/internal/repo"
	"go-simple-api/internal/services"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepo := repo.NewUserRepository()
	iUserService := services.NewUserService(iUserRepo)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
